kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ include "uumssql.fullname" . }}-config
data:
  mssql.conf: |
    [filelocation]
    defaultdatadir = /var/opt/mssql/data
    defaultlogdir = /var/opt/mssql/log
    {{- .Values.config.mssqlConf | nindent 4 -}}