{{- $secretName := printf "%s-secret" (include "uumssql.fullname" .) -}}

{{- $ex := lookup "v1" "Secret" .Release.Namespace $secretName -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "uumssql.labels" . | nindent 4 }}
type: Opaque
data:
{{- if not $ex }}
  password : {{ randAscii 16 | b64enc }}
{{- else }}
  password: {{ $ex.data.password }}
{{- end -}}