apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uumssql.fullname" . }}-secret
  labels:
    {{- include "uumssql.labels" . | nindent 4 }}
type: Opaque
data:
  password : {{ randAlphaNum 12 | b64enc }}