apiVersion: v1
kind: Service
metadata:
  name: {{ include "uumssql.fullname" . }}
  labels:
    {{- include "uumssql.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1433
      protocol: TCP
      name: ms-sql-s
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "uumssql.selectorLabels" . | nindent 4 }}

---

# Headless service for stable DNS entries of StatefulSet members
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uumssql.fullname" . }}-headless
  labels:
    {{- include "uumssql.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | indent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1433
      protocol: TCP
      name: ms-sql-s
    {{- if .Values.extraPorts }}
    {{- toYaml .Values.extraPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "uumssql.selectorLabels" . | nindent 4 }}
