apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "uumssql.fullname" . }}
  labels:
    {{- include "uumssql.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "uumssql.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "uumssql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "uumssql.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "uumssql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- if .Values.extraInitContainers }}
      initContainers:
        {{- toYaml .Values.extraInitContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /bin/bash
            - -c
            - cp /var/opt/config/mssql.conf /var/opt/mssql/mssql.conf && /opt/mssql/bin/sqlservr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 1433
          env:
            {{- if .Values.extraEnvs }}
              {{- toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
            - name: MSSQL_PID
              value: {{ .Values.config.edition | quote }}
            - name: ACCEPT_EULA
              value: {{- if .Values.config.acceptEula }} "Y"{{- else}} "N"{{- end }}
            - name: MSSQL_AGENT_ENABLED
              value: {{ .Values.config.agent_enabled | quote }}
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "uumssql.fullname" . }}-secret
                  key: password
          volumeMounts:
            - name: {{ include "uumssql.fullname" . }}-data
              mountPath: "/var/opt/mssql"
            - name: config
              mountPath: /var/opt/config
          {{- if .Values.resources }}
          resourses:
            {{- toYaml .Values.resources | indent 12 }}
          {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      volumes:        
        - name: config
          configMap:
            name: {{ include "uumssql.fullname" . }}-config
  {{- if .Values.persistance.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "uumssql.fullname" . }}-data
        annotations: 
          {{- toYaml .Values.persistance.annotations | nindent 10 }}
      spec:
        {{- if .Values.persistance.storageClass -}}
        storageClassName: {{ .Values.persistance.storageClass }}
        {{- end }}
        accessModes:
          {{ toYaml .Values.persistance.accessModes }}
        resources:
          requests:
            storage: {{ .Values.persistance.sizeLimit | default "5Gi" }}
{{- else }}
        - name: {{ include "uumssql.fullname" . }}-data
          emptyDir:
            {{- if .Values.persistance.sizeLimit }}
            sizeLimit: {{ .Values.persistance.sizeLimit }}
            {{- else }}
              {}
            {{- end }}
{{- end }}